### ISSUE TITLE
重名歌曲过多搜索不到原曲

### ISSUE THREAD

**Issue by neking2003** [Xposed-Modules-Repo/com.blanke.diaomao163#15]
歌名《梦想的旗帜》
既是snh48的公演名，也是其中的一首同名歌曲。默认播放的是该公演的其他歌曲《星座》，点击歌名搜索，出现的均是该公演其他歌曲（因为专辑名都叫《梦想的旗帜（xx版）》，反而没有这首同名歌曲。长按歌名还原，播放的也是《星座》
建议要么优先歌名完全匹配，要么允许翻页
另，咪咕源搜索提示“搜索出错：请求失败［500］”，即使第一个就是原曲也无法播放

**Comment by Blankeer** [comment]
点击歌名搜索 默认是歌曲名，后面加上歌手名字，试试。还不行的话，可能 kuwo 没有这首歌

**Comment by wiidede** [comment]
> 点击歌名搜索 默认是歌曲名，后面加上歌手名字，试试。还不行的话，可能 kuwo 没有这首歌

我也经常手动替换，就是加上作者名。所以默认匹配歌曲的时候，能不能带上作者的信息呢，这样准确率会高一点？
